name: Ensure dev is up-to-date

on:
  push:
    branches: [ "main" ]

jobs:
  update-dev:
    uses: ./.github/workflows/open-pr.yml
    with:
      branch: main
      dest: devel
    secrets: inherit
