# This is a basic workflow to help you get started with Actions

name: Ensure dev is up-to-date

on:
  push:
    branches: [ "main" ]

env:
  MAIN_BRANCH: main
  DEV_BRANCH: devel

jobs:
  create-dev-pr:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Check for PRs from main to dev
        id: check
        run: >
          echo "::set-output name=open_prs::$(gh pr list --base $DEV_BRANCH --head $MAIN_BRANCH)"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create a pull request for updating dev branch with main branch
        run: >
          gh pr create
          --base $DEV_BRANCH
          --head $MAIN_BRANCH
          --title "Backport: $(git log --format='%s' -1)"
          --body "Changes from $MAIN_BRANCH.\n\n**Do not use squash when merging!**"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # only if there is no PR already opened
        if: steps.check.outputs.open_prs == ''
