name: Create a pull request

on:
  workflow_call:
    inputs:
      dest:
        required: true
        type: string
      branch:
        required: true
        type: string

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Fetch all branches
        run: git fetch

      - name: branches
        run: |
          git branch -a
          git remote -v
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Check for changes
        id: diff
        run: |
          git diff --exit-code origin/${{ inputs.dest }} origin/${{ inputs.branch }}
          echo "rc=$?" >> $GITHUB_OUTPUT
          git diff --exit-code origin/${{ inputs.dest }} origin/${{ inputs.dest }}
          echo "ook=$?" >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: test
        run: echo ook 1
        if: steps.diff.outputs.ook == '1'

      - name: test
        run: echo ook 0
        if: steps.diff.outputs.ook == '0'


      - name: test
        run: echo rc 1
        if: steps.diff.outputs.rc == '1'

      - name: test
        run: echo rc 0
        if: steps.diff.outputs.rc == '0'

      - name: Check for open PRs from ${{ inputs.branch }} to ${{ inputs.dest }}
        id: check
        run: |
          PRs=$(gh pr list --base ${{ inputs.dest }} --head ${{ inputs.branch }})
          echo $PRs
          echo "open_prs=$PRs" >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create a PR for updating ${{ inputs.dest }} with ${{ inputs.branch }}
        run: >
          gh pr create
          --base ${{ inputs.dest }}
          --head ${{ inputs.branch }}
          --title "Backport changes from ${{ inputs.branch }} to ${{ inputs.dest }}"
          --body "Some commits were merged into ${{ inputs.branch }},
          so ${{ inputs.dest }} should get them, too.

          **Do not use squash-merge on this PR!**"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # only if there is no PR already opened
        if: steps.check.outputs.open_prs == ''
