name: Open a PR ${{ inputs.base }}

on:
  workflow_call:
    inputs:
      base:
        required: true
        type: string
      head:
        required: true
        type: string

env:
  MAIN_BRANCH: ${{ inputs.head }}
  DEV_BRANCH: ${{ inputs.base }}

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Check for PRs from ${{ inputs.head }} to ${{ inputs.base }}
        id: check
        run: >
          echo "::set-output name=open_prs::$(gh pr list --base $DEV_BRANCH --head $MAIN_BRANCH)"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create a pull request for updating dev branch with main branch
        run: >
          gh pr create
          --base $DEV_BRANCH
          --head $MAIN_BRANCH
          --title "Backport changes from $MAIN_BRANCH to $DEV_BRANCH"
          --body "Some commits were merged into $MAIN_BRANCH, so $DEV_BRANCH should get them, too.

          **Do not use squash-merge on this PR!**"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # only if there is no PR already opened
        if: steps.check.outputs.open_prs == ''
